
const blogData = [

    {
        id:1,
        title:'post-one',
        image: "/src/assets/h-c-1.png",
        category:"Technology",
        author:"Jhonson Doe",
        authorInfo:"Programmer & Developer",
        content:"The Impact of Technology on the Workplace: How Technology is Changing",
        Authorimage:"/src/assets/au-1.png",
        info:"August 20, 2022",
        detailedInfo:"Traveling is an enriching experience that opens up new horizons, exposes us to different cultures, and creates memories that last a lifetime. However, traveling can also be stressful and overwhelming, especially if you don't plan and prepare adequately. In this blog article, we'll explore tips and tricks for a memorable journey and how to make the most of your travels",
        detailedInfos:"One of the most rewarding aspects of traveling is immersing yourself in the local culture and customs. This includes trying local cuisine, attending cultural events and festivals, and interacting with locals. Learning a few phrases in the local language can also go a long way in making connections and showing respect.",
        detailedHead:"Research Your Destination",
        detailedHead2:"Plan Your Itinerary",
        detailedHead3:"Pack Lightly and Smartly",
        detailedHead4:"Immerse Yourself in the Local Culturey",
        detailedHead5:"Capture Memories",
        detailedHead6:"Conclusion:"



    },
    {
        id:2,
        title:'post-two',
        image: "/src/assets/h-c-2.png",
        category:"Technology",
        author:"Alen franki",
        authorInfo:"Programmer & Developer",
        content:"The Impact of Technology on the Workplace: How Technology is Changing",
        Authorimage:"/src/assets/au-2.png",
        info:"August 20, 2024",
        detailedInfo:"Traveling is an enriching experience that opens up new horizons, exposes us to different cultures, and creates memories that last a lifetime. However, traveling can also be stressful and overwhelming, especially if you don't plan and prepare adequately. In this blog article, we'll explore tips and tricks for a memorable journey and how to make the most of your travelsOne of the most rewarding aspects of traveling is immersing yourself in the local culture and customs. This includes trying local cuisine, attending cultural events and festivals, and interacting with locals. Learning a few phrases in the local language can also go a long way in making connections and showing respect.",
        detailedHead:"Research Your Destination",
        detailedHead2:"Plan Your Itinerary",
        detailedHead3:"Pack Lightly and Smartly",
        detailedHead4:"Immerse Yourself in the Local Culturey",
        detailedHead5:"Capture Memories",
        detailedHead6:"Conclusion:"
    },
    {
        id:3,
        title:'post-three',
        image: "/src/assets/h-c-3.png",
        category:"Technology",
        author:"Jhonson Doe",
        authorInfo:"Programmer & Developer",
        content:"The Impact of Technology on the Workplace: How Technology is Changing",
        Authorimage:"/src/assets/au-3.png",
        info:"August 20, 2022",
        detailedInfo:"Traveling is an enriching experience that opens up new horizons, exposes us to different cultures, and creates memories that last a lifetime. However, traveling can also be stressful and overwhelming, especially if you don't plan and prepare adequately. In this blog article, we'll explore tips and tricks for a memorable journey and how to make the most of your travels",
        detailedInfos:"One of the most rewarding aspects of traveling is immersing yourself in the local culture and customs. This includes trying local cuisine, attending cultural events and festivals, and interacting with locals. Learning a few phrases in the local language can also go a long way in making connections and showing respect.",
        detailedHead:"Research Your Destination",
        detailedHead2:"Plan Your Itinerary",
        detailedHead3:"Pack Lightly and Smartly",
        detailedHead4:"Immerse Yourself in the Local Culturey",
        detailedHead5:"Capture Memories",
        detailedHead6:"Conclusion:"
    },
    {
        id:4,
        title:'post-four',
        image: "/src/assets/h-c-4.png",
        category:"Economy",
        author:"Jason Frankalio",
        authorInfo:"Economist & Social Analytics",
        content:"The Impact of Economy on the Workplace: How Technology is Changing",
        Authorimage:"/src/assets/au-1.png",
        info:"August 20, 2021",
        detailedInfo:"Traveling is an enriching experience that opens up new horizons, exposes us to different cultures, and creates memories that last a lifetime. However, traveling can also be stressful and overwhelming, especially if you don't plan and prepare adequately. In this blog article, we'll explore tips and tricks for a memorable journey and how to make the most of your travels",
        detailedInfos:"One of the most rewarding aspects of traveling is immersing yourself in the local culture and customs. This includes trying local cuisine, attending cultural events and festivals, and interacting with locals. Learning a few phrases in the local language can also go a long way in making connections and showing respect.",
        detailedHead:"Research Your Destination",
        detailedHead2:"Plan Your Itinerary",
        detailedHead3:"Pack Lightly and Smartly",
        detailedHead4:"Immerse Yourself in the Local Culturey",
        detailedHead5:"Capture Memories",
        detailedHead6:"Conclusion:"
    },
    {
        id:5,
        title:'post-one',
        image: "/src/assets/h-c-5.png",
        category:"Economy",
        author:"Alen franki",
        authorInfo:"Economist & Social Analytics",
        content:"The Impact of Economy on the Workplace: How Technology is Changing",
        Authorimage:"/src/assets/au-2.png",
        info:"June 10, 2005",
        detailedInfo:"Traveling is an enriching experience that opens up new horizons, exposes us to different cultures, and creates memories that last a lifetime. However, traveling can also be stressful and overwhelming, especially if you don't plan and prepare adequately. In this blog article, we'll explore tips and tricks for a memorable journey and how to make the most of your travelsOne of the most rewarding aspects of traveling is immersing yourself in the local culture and customs. This includes trying local cuisine, attending cultural events and festivals, and interacting with locals. Learning a few phrases in the local language can also go a long way in making connections and showing respect.",
        detailedHead:"Research Your Destination",
        detailedHead2:"Plan Your Itinerary",
        detailedHead3:"Pack Lightly and Smartly",
        detailedHead4:"Immerse Yourself in the Local Culturey",
        detailedHead5:"Capture Memories",
        detailedHead6:"Conclusion:"
    },
    {
        id:6,
        title:'post-six',
        image: "/src/assets/h-c-6.png",
        category:"Economy",
        author:"Jhonson Doe",
        authorInfo:"Economist & Social Analytics",
        content:"The Impact of Economy on the Workplace: How Technology is Changing",
        Authorimage:"/src/assets/au-3.png",
        info:"May 20, 2022",detailedInfo:"Traveling is an enriching experience that opens up new horizons, exposes us to different cultures, and creates memories that last a lifetime. However, traveling can also be stressful and overwhelming, especially if you don't plan and prepare adequately. In this blog article, we'll explore tips and tricks for a memorable journey and how to make the most of your travels",
        detailedInfos:"One of the most rewarding aspects of traveling is immersing yourself in the local culture and customs. This includes trying local cuisine, attending cultural events and festivals, and interacting with locals. Learning a few phrases in the local language can also go a long way in making connections and showing respect.",
        detailedHead:"Research Your Destination",
        detailedHead2:"Plan Your Itinerary",
        detailedHead3:"Pack Lightly and Smartly",
        detailedHead4:"Immerse Yourself in the Local Culturey",
        detailedHead5:"Capture Memories",
        detailedHead6:"Conclusion:"
    },
    {
        id:7,
        title:'post-sev',
        image: "/src/assets/h-c-7.png",
        category:"Politics",
        author:"Jhonson Doe",
        authorInfo:"Political Science & Editor",
        content:"The Impact of Politics on the Workplace: How Technology is Changing",
        Authorimage:"/src/assets/au-1.png",
        info:"August 20, 2022",
        detailedInfo:"Traveling is an enriching experience that opens up new horizons, exposes us to different cultures, and creates memories that last a lifetime. However, traveling can also be stressful and overwhelming, especially if you don't plan and prepare adequately. In this blog article, we'll explore tips and tricks for a memorable journey and how to make the most of your travels",
        detailedInfos:"One of the most rewarding aspects of traveling is immersing yourself in the local culture and customs. This includes trying local cuisine, attending cultural events and festivals, and interacting with locals. Learning a few phrases in the local language can also go a long way in making connections and showing respect.",
        detailedHead:"Research Your Destination",
        detailedHead2:"Plan Your Itinerary",
        detailedHead3:"Pack Lightly and Smartly",
        detailedHead4:"Immerse Yourself in the Local Culturey",
        detailedHead5:"Capture Memories",
        detailedHead6:"Conclusion:"
    },
    {
        id:8,
        title:'post-eight',
        image: "./src/assets/h-c-8.png",
        category:"Politics",
        author:"Jason Frankalio",
        authorInfo:"Collaborator & Editor",
        content:"The Impact of Politics on the Workplace: How Technology is Changing",
        Authorimage:"/src/assets/au-2.png",
        info:"August 20, 2022",
        detailedInfo:"Traveling is an enriching experience that opens up new horizons, exposes us to different cultures, and creates memories that last a lifetime. However, traveling can also be stressful and overwhelming, especially if you don't plan and prepare adequately. In this blog article, we'll explore tips and tricks for a memorable journey and how to make the most of your travels",
        detailedInfos:"One of the most rewarding aspects of traveling is immersing yourself in the local culture and customs. This includes trying local cuisine, attending cultural events and festivals, and interacting with locals. Learning a few phrases in the local language can also go a long way in making connections and showing respect.",
        detailedHead:"Research Your Destination",
        detailedHead2:"Plan Your Itinerary",
        detailedHead3:"Pack Lightly and Smartly",
        detailedHead4:"Immerse Yourself in the Local Culturey",
        detailedHead5:"Capture Memories",
        detailedHead6:"Conclusion:"
    },
    {
        id:9,
        title:'post-nine',
        image: "/src/assets/h-c-9.png",

        category:"Politics",
        author:"Jason Frankalio",
        authorInfo:"Political Science & Editor",
        content:"The Impact of Politics on the Workplace: How Technology is Changing",
        Authorimage:"/src/assets/au-3.png",
        info:"August 20, 2022",detailedInfo:"Traveling is an enriching experience that opens up new horizons, exposes us to different cultures, and creates memories that last a lifetime. However, traveling can also be stressful and overwhelming, especially if you don't plan and prepare adequately. In this blog article, we'll explore tips and tricks for a memorable journey and how to make the most of your travels",
        detailedInfos:"One of the most rewarding aspects of traveling is immersing yourself in the local culture and customs. This includes trying local cuisine, attending cultural events and festivals, and interacting with locals. Learning a few phrases in the local language can also go a long way in making connections and showing respect.",
        detailedHead:"Research Your Destination",
        detailedHead2:"Plan Your Itinerary",
        detailedHead3:"Pack Lightly and Smartly",
        detailedHead4:"Immerse Yourself in the Local Culturey",
        detailedHead5:"Capture Memories",
        detailedHead6:"Conclusion:"
    },{
        id:10,
        title:'post-one',
        image: "/src/assets/h-c-1.png",
        category:"Technology",
        author:"Jhonson Doe",
        authorInfo:"Collaborator & Editor",
        content:"The Impact of Technology on the Workplace: How Technology is Changing",
        Authorimage:"/src/assets/au-1.png",
        info:"August 20, 2022",detailedInfo:"Traveling is an enriching experience that opens up new horizons, exposes us to different cultures, and creates memories that last a lifetime. However, traveling can also be stressful and overwhelming, especially if you don't plan and prepare adequately. In this blog article, we'll explore tips and tricks for a memorable journey and how to make the most of your travels",
        detailedInfos:"One of the most rewarding aspects of traveling is immersing yourself in the local culture and customs. This includes trying local cuisine, attending cultural events and festivals, and interacting with locals. Learning a few phrases in the local language can also go a long way in making connections and showing respect.",
        detailedHead:"Research Your Destination",
        detailedHead2:"Plan Your Itinerary",
        detailedHead3:"Pack Lightly and Smartly",
        detailedHead4:"Immerse Yourself in the Local Culturey",
        detailedHead5:"Capture Memories",
        detailedHead6:"Conclusion:"

    },
    {
        id:11,
        title:'post-nine',
        image: "/src/assets/h-c-9.png",
        category:"Politics",
        author:"Jason Frankalio",
        authorInfo:"Collaborator & Editor",
        content:"The Impact of Politics on the Workplace: How Technology is Changing",
        Authorimage:"/src/assets/au-3.png",
        info:"August 20, 2022"
    },
    {
        id:12,
        title:'post-six',
        image: "/src/assets/h-c-6.png",
        category:"Economy",
        author:"Jhonson Doe",
        authorInfo:"Collaborator & Editor",
        content:"The Impact of Economy on the Workplace: How Technology is Changing",
        Authorimage:"/src/assets/au-3.png",
        info:"May 20, 2022",detailedInfo:"Traveling is an enriching experience that opens up new horizons, exposes us to different cultures, and creates memories that last a lifetime. However, traveling can also be stressful and overwhelming, especially if you don't plan and prepare adequately. In this blog article, we'll explore tips and tricks for a memorable journey and how to make the most of your travels",
        detailedInfos:"One of the most rewarding aspects of traveling is immersing yourself in the local culture and customs. This includes trying local cuisine, attending cultural events and festivals, and interacting with locals. Learning a few phrases in the local language can also go a long way in making connections and showing respect.",
        detailedHead:"Research Your Destination",
        detailedHead2:"Plan Your Itinerary",
        detailedHead3:"Pack Lightly and Smartly",
        detailedHead4:"Immerse Yourself in the Local Culturey",
        detailedHead5:"Capture Memories",
        detailedHead6:"Conclusion:"
    }
]
export default blogData